In [2]:
import numpy as np

In [38]:
def dec2bin(arg, bits):
    func = lambda x: np.array(list(f'{bin(x)[2:]:0>{bits}s}'), 'int32')
    if isinstance(arg, np.ndarray):
        return np.array([func(x) for x in arg])
    elif isinstance(arg, list):
        return np.array([func(x) for x in arg])
    else:
        return func(arg)

In [58]:
dec2bin(35, 6)

array([1, 0, 0, 0, 1, 1], dtype=int32)

In [59]:
dec2bin([155,65], 8)

array([[1, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 1]], dtype=int32)

In [60]:
dec2bin(np.array([128,200,12]), 8)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0]], dtype=int32)

In [21]:
def bin2dec(arg):
    func = lambda x: sum([bit*2**(len(x)-1-t) for t, bit in enumerate(x)])
    if isinstance(arg, list):
        return func(arg)
    else:
        if len(np.shape(arg))==1:
            return int(func(arg))
        else:
            return np.array([func(x) for x in arg])

In [84]:
bin2dec([1, 0, 1])

5

In [88]:
bin2dec(np.array([1,0,0,0,1,1]))

35

In [89]:
bin2dec(np.array([[1,0,0,1,1,0,1,1],
                  [0,1,0,0,0,0,0,1]]))

array([155,  65])

In [90]:
bin2dec(np.array([[1,0,0,0,0,0,0,0],
                  [1,1,0,0,1,0,0,0],
                  [0,0,0,0,1,1,0,0]]))

array([128, 200,  12])

In [11]:
def lsbget(p, m):
    if isinstance(p, int):
        return dec2bin(p, 8)[-m:]
    else:
        return np.array([x[-m:] for x in dec2bin(p, 8)])

In [4]:
lsbget(157, 3)

array([1, 0, 1], dtype=int32)

In [12]:
lsbget([92, 129], 4)

array([[1, 1, 0, 0],
       [0, 0, 0, 1]], dtype=int32)

In [13]:
lsbget(np.array([92, 129, 83]), 2)

array([[0, 0],
       [0, 1],
       [1, 1]], dtype=int32)

In [ ]:
def lsbset(p, bits):
    if isinstance(p, int):
        tmp = dec2bin(p, 8)
        for idx, bit in enumerate(bits):
            tmp[-len(bits)+idx] = bit
        return bin2dec(tmp)
    else:
        arr = np.array([None]*len(p))
        for i, m in enumerate(bits):
            tmp = dec2bin(p[i], 8)
            for idx, bit in enumerate(m):
                tmp[-len(m)+idx] = bit
            arr[i] = bin2dec(tmp)
        return arr

In [31]:
lsbset(155, [1,0,1])

157

In [32]:
lsbset([155,41],[[1,0,1],[0,1,0]])

array([157, 42], dtype=object)

In [39]:
lsbset(np.array([140,33,158]), np.array([[0,1],[0,0],[1,1]]))

array([141, 32, 159], dtype=object)