In [10]:
import numpy as np

### 1.1

In [50]:
def dec2bin(arg, bits):
    func = lambda x: np.array(list(f'{bin(x)[2:]:0>{bits}s}'), 'int32')
    if isinstance(arg, np.ndarray):
        return np.array([func(x) for x in arg])
    elif isinstance(arg, list):
        return np.array([func(x) for x in arg])
    else:
        return func(arg)

In [51]:
dec2bin(35, 6)

array([1, 0, 0, 0, 1, 1], dtype=int32)

In [52]:
dec2bin([155,65], 8)

array([[1, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 1]], dtype=int32)

In [53]:
dec2bin(np.array([128,200,12]), 8)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0]], dtype=int32)

### 1.2

In [15]:
def bin2dec(arg):
    func = lambda x: sum([bit*2**(len(x)-1-t) for t, bit in enumerate(x)])
    if isinstance(arg, list):
        return func(arg)
    else:
        if len(np.shape(arg))==1:
            return int(func(arg))
        else:
            return np.array([func(x) for x in arg])

In [16]:
bin2dec([1, 0, 1])

5

In [17]:
bin2dec(np.array([1,0,0,0,1,1]))

35

In [18]:
bin2dec(np.array([[1,0,0,1,1,0,1,1],
                  [0,1,0,0,0,0,0,1]]))

array([155,  65])

In [19]:
bin2dec(np.array([[1,0,0,0,0,0,0,0],
                  [1,1,0,0,1,0,0,0],
                  [0,0,0,0,1,1,0,0]]))

array([128, 200,  12])

### 1.3

In [20]:
def lsbget(p, m):
    if isinstance(p, int):
        return dec2bin(p, 8)[-m:]
    else:
        return np.array([x[-m:] for x in dec2bin(p, 8)])

In [21]:
lsbget(157, 3)

array([1, 0, 1], dtype=int32)

In [22]:
lsbget([92, 129], 4)

array([[1, 1, 0, 0],
       [0, 0, 0, 1]], dtype=int32)

In [23]:
lsbget(np.array([92, 129, 83]), 2)

array([[0, 0],
       [0, 1],
       [1, 1]], dtype=int32)

### 1.4

In [24]:
def lsbset(p, bits):
    if isinstance(p, int):
        tmp = dec2bin(p, 8)
        for idx, bit in enumerate(bits):
            tmp[-len(bits)+idx] = bit
        return bin2dec(tmp)
    else:
        arr = np.array([None]*len(p))
        for i, m in enumerate(bits):
            tmp = dec2bin(p[i], 8)
            for idx, bit in enumerate(m):
                tmp[-len(m)+idx] = bit
            arr[i] = bin2dec(tmp)
        return arr

In [25]:
lsbset(155, [1,0,1])

157

In [26]:
lsbset([155,41],[[1,0,1],[0,1,0]])

array([157, 42], dtype=object)

In [27]:
lsbset(np.array([140,33,158]), np.array([[0,1],[0,0],[1,1]]))

array([141, 32, 159], dtype=object)

### 1.5

In [ ]:
def bitget(p, k):
    func = lambda: (p>>k)%2
    if isinstance(p, int):
        return func()
    else:
        if isinstance(p, list):
            p = np.array(p)
        return func()

In [57]:
bitget(155, 5)

0

In [58]:
bitget([155,74], 1)

array([1, 1])

In [59]:
bitget(np.array([69,82,90]), 7)

array([0, 0, 0])

In [60]:
bitget(np.array([[69, 82],
                [90,128]]), 0)

array([[1, 0],
       [0, 0]])

### 1.6

In [81]:
def bitset(p, k, v):
    check = lambda: (p>>k)%2
    func1 = lambda:p + (-2**k if check() and (check() ^ v) else 2**k if check() ^ v else 0)
    func2 = lambda:p + np.where(check() & (check() ^ v), -2**k, 0) + np.where(~check() & (check() ^ v), 2**k, 0)
    if isinstance(p, int):
        return func1()
    else:
        if isinstance(p, list):
            p = np.array(p)
            v = np.array(v)
        return func2()

In [69]:
bitset(12,0,1)

13

In [82]:
bitset([12,13],7,[1,0])

array([140,  13])

In [85]:
bitset(np.array([[69,82],[90,128]]), 0, np.array([[0,1],[1,0]]))

array([[ 68,  83],
       [ 91, 128]])